#:schema node_modules/wrangler/config-schema.json
name = "botified-chat"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "pnpm run build"

compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai
[ai]
binding = "AI"

[[d1_databases]]
binding = "PRIMARY_DB"
database_name = "botified-dev-db"
database_id = "3762caf8-10f8-48ca-9b2d-aff37700c6fc"

[[d1_databases]]
binding = "CHAT_DB"
database_name = "botified-dev-chat-db"
database_id = "97df7213-e09f-4275-9d03-6a7c01587b70"

[[kv_namespaces]]
binding = "BOTIFIED_KV"
id = "997e8726cb0c483cacc98ac0a50fe850"
preview_id = "997e8726cb0c483cacc98ac0a50fe850"

[[vectorize]]
binding = "BOTIFIED_VECTOR"
index_name = "botified-vector-db-dev"

[[r2_buckets]]
binding = "PRIVATE_BUCKET"
bucket_name = "botified-chat-private-dev"
preview_bucket_name = "preview-botified-chat-private-dev"

[[r2_buckets]]
binding = "PUBLIC_BUCKET"
bucket_name = "botified-chat-public-dev"
preview_bucket_name = "preview-botified-chat-public-dev"


#[env.prod]
#name = "botified-chat"
#
#[[r2_buckets]]
#binding = "PRIVATE_BUCKET"
#bucket_name = "botified-chat-private-dev"
#
#[[r2_buckets]]
#binding = "PUBLIC_BUCKET"
#bucket_name = "botified-chat-public-dev"
#
#[[kv_namespaces]]
#binding = "BOTIFIED_KV"
#id = "5010f95929224d02969b4dac3af16b99"
#
#[[vectorize]]
#binding = "BOTIFIED_VECTOR"
#index_name = "botified-vector-db-dev"
#
#[[d1_databases]]
#binding = "PRIMARY_DB"
#database_name = "botified-dev-db"
#database_id = "3762caf8-10f8-48ca-9b2d-aff37700c6fc"
#
#[[d1_databases]]
#binding = "CHAT_DB"
#database_name = "botified-dev-chat-db"
#database_id = "97df7213-e09f-4275-9d03-6a7c01587b70"